export const MODES = [
  { id: 'mimica',   icon: 'masks',  name: 'Mímica',    desc: 'Atue sem falar nem apontar.',       tint: '#10bcd7' },
  { id: 'desenho',  icon: 'pencil', name: 'Desenho',   desc: 'Desenhe para o time adivinhar.',     tint: '#57bf95' },
  { id: 'descreva', icon: 'speech', name: 'Descreva',  desc: 'Explique sem dizer a palavra.',      tint: '#ff7a3d' },
  { id: 'turbo',    icon: 'bolt',   name: 'Turbo',     desc: 'Rodadas relâmpago de 30 segundos.', tint: '#ffc83d' },
]

export const PACKS = [
  { id: 'animais',    emoji: '🐵', name: 'Animais',     free: true,
    words: ['Macaco','Elefante','Pinguim','Girafa','Golfinho','Camaleão','Preguiça','Tubarão','Coruja','Ouriço',
      'Canguru','Polvo','Leão','Tigre','Zebra','Cavalo','Cachorro','Gato','Coelho','Tartaruga','Cobra','Crocodilo',
      'Rinoceronte','Hipopótamo','Urso','Panda','Coala','Lobo','Raposa','Esquilo','Morcego','Águia','Papagaio',
      'Flamingo','Pavão','Borboleta','Abelha','Aranha','Caranguejo','Baleia','Foca','Formiga','Joaninha','Sapo',
      'Jacaré','Camelo','Avestruz'] },
  { id: 'filmes',     emoji: '🎬', name: 'Filmes',      free: true,
    words: ['Titanic','Rei Leão','Matrix','Toy Story','Vingadores','Jurassic Park','Frozen','Velozes e Furiosos',
      'Avatar','Star Wars','Harry Potter','Senhor dos Anéis','Procurando Nemo','Divertida Mente','Shrek',
      'Piratas do Caribe','De Volta para o Futuro','O Poderoso Chefão','Cidade de Deus','Tropa de Elite',
      'Meu Malvado Favorito','Rocky','Gladiador','Exterminador do Futuro','A Bela e a Fera','Aladdin','Cinderela',
      'Os Incríveis','Wall-E','Up: Altas Aventuras','Kung Fu Panda','Madagascar','A Era do Gelo','Interestelar',
      'Jumanji','King Kong','Zootopia','Detona Ralph','Como Treinar o seu Dragão'] },
  { id: 'profissoes', emoji: '👩‍🚀', name: 'Profissões', free: true,
    words: ['Astronauta','Bombeiro','Chef','Dentista','Piloto','Mágico','Jardineiro','DJ','Veterinário','Detetive',
      'Médico','Enfermeiro','Professor','Advogado','Juiz','Policial','Cozinheiro','Padeiro','Açougueiro','Pescador',
      'Agricultor','Pintor','Escultor','Músico','Cantor','Ator','Palhaço','Bailarino','Fotógrafo','Jornalista',
      'Escritor','Cientista','Engenheiro','Arquiteto','Eletricista','Encanador','Mecânico','Carteiro','Barbeiro',
      'Cabeleireiro','Costureira','Garçom','Motorista','Marinheiro','Soldado','Astrônomo','Domador','Mergulhador'] },
  { id: 'acoes',      emoji: '🤸', name: 'Ações',       free: true,
    words: ['Dançar','Escalar','Cozinhar','Esquiar','Surfar','Bocejar','Espirrar','Pescar','Costurar','Patinar',
      'Correr','Pular','Nadar','Dormir','Chorar','Rir','Gritar','Assobiar','Aplaudir','Cochichar','Abraçar','Cair',
      'Tropeçar','Dirigir','Voar','Cavar','Martelar','Varrer','Lavar','Escovar os dentes','Amarrar o sapato','Ler',
      'Escrever','Desenhar','Fotografar','Digitar','Telefonar','Cantar','Tocar violão','Boxear','Remar','Pedalar',
      'Meditar','Espreguiçar','Mergulhar','Espiar','Fugir','Rastejar'] },
  { id: 'objetos',    emoji: '🪑', name: 'Objetos',     free: false,
    words: ['Guarda-chuva','Liquidificador','Telescópio','Ampulheta','Despertador','Bússola','Vassoura','Escova',
      'Guarda-roupa','Geladeira','Ventilador','Chuveiro','Torradeira','Microfone','Câmera','Balança','Lanterna',
      'Vela','Chave','Cadeado','Escada','Regador','Binóculo','Lupa','Termômetro','Balde','Corda','Pipa','Mochila',
      'Carteira','Relógio','Espelho','Travesseiro','Cobertor','Xícara','Garfo','Colher'] },
  { id: 'famosos',    emoji: '⭐', name: 'Famosos',     free: false,
    words: ['Pelé','Einstein','Chaplin','Frida Kahlo','Mozart','Cleópatra','Newton','Shakespeare','Da Vinci','Picasso',
      'Van Gogh','Beethoven','Gandhi','Napoleão','Nelson Mandela','Michael Jackson','Elvis Presley','Marilyn Monroe',
      'Ayrton Senna','Santos Dumont','Tarsila do Amaral','Machado de Assis','Monteiro Lobato','Carmen Miranda',
      'Tom Jobim','Chico Buarque','Xuxa','Silvio Santos','Neymar','Ronaldo','Marta','Gisele Bündchen','Anitta',
      'Roberto Carlos','Zico','Ronaldinho Gaúcho','Oscar Niemeyer','Getúlio Vargas','Tiradentes','Dom Pedro I',
      'Princesa Isabel','Galileu','Darwin','Marie Curie','Steve Jobs','Walt Disney','Cazuza','Freddie Mercury'] },
  { id: 'comidas',    emoji: '🍕', name: 'Comidas',     free: false,
    words: ['Pizza','Brigadeiro','Sushi','Pipoca','Lasanha','Açaí','Cachorro-quente','Picolé','Hambúrguer','Feijoada',
      'Coxinha','Pão de queijo','Pastel','Tapioca','Churrasco','Farofa','Mandioca','Sorvete','Bolo','Pudim','Beijinho',
      'Cocada','Torta','Salada','Espaguete','Panqueca','Omelete','Sanduíche','Taco','Burrito','Sopa','Risoto','Camarão',
      'Salmão','Chocolate','Chiclete','Bolacha','Rosquinha','Cupcake','Waffle','Milkshake','Suco','Café','Vitamina',
      'Queijo','Ovo frito','Arroz','Feijão'] },
  { id: 'lugares',    emoji: '🗺️', name: 'Lugares',     free: false,
    words: ['Praia','Deserto','Floresta','Vulcão','Museu','Aeroporto','Caverna','Castelo','Montanha','Ilha','Cachoeira',
      'Rio','Lago','Ponte','Farol','Igreja','Estádio','Cinema','Shopping','Hospital','Escola','Biblioteca','Zoológico',
      'Circo','Parque','Fazenda','Selva','Geleira','Pirâmide','Torre Eiffel','Cristo Redentor','Muralha da China',
      'Coliseu','Amazônia','Pantanal','Cataratas','Polo Norte','Lua','Marte','Restaurante','Padaria','Mercado','Teatro',
      'Aquário','Planetário','Deserto do Saara','Praça','Metrô'] },
  { id: 'lendas',     emoji: '🧚', name: 'Lendas',      free: true,
    words: ['Saci-Pererê','Curupira','Iara','Boitatá','Mula sem Cabeça','Boto Cor-de-rosa','Cuca','Lobisomem',
      'Caipora','Mãe-d\'Água','Negrinho do Pastoreio','Bumba Meu Boi','Mapinguari','Cobra Grande','Corpo-Seco',
      'Pisadeira','Anhangá','Jurupari','Uirapuru','Vitória-Régia','Matinta Pereira','Cabra-Cabriola',
      'Comadre Fulôzinha','Boiúna','Romãozinho','Papa-Figo','Quibungo','Bicho-Papão','Sereia','Minhocão',
      'Nego d\'Água','Cabeça-de-Cuia','Muiraquitã','Besta-Fera','Tutu Marambá','Lenda do Guaraná',
      'Lenda da Mandioca','Ipupiara','Jaci','Guaraci'] },
  { id: 'personagens', emoji: '🎭', name: 'Personagens', free: true,
    words: ['Mickey Mouse','Pato Donald','Pernalonga','Bob Esponja','Homer Simpson','Pikachu','Super Mario','Sonic',
      'Woody','Buzz Lightyear','Simba','Elsa','Olaf','Nemo','Dory','Ariel','Gênio','Mogli','Peter Pan','Pinóquio',
      'Branca de Neve','Rapunzel','Moana','Minions','Po','Scooby-Doo','Popeye','Tom e Jerry','Pica-Pau','Mônica',
      'Cebolinha','Cascão','Magali','Zé Colmeia','Fred Flintstone','Garfield','Snoopy','Yoda','Darth Vader','Gandalf'] },
  { id: 'paises',     emoji: '🌍', name: 'Países',      free: true,
    words: ['Brasil','Argentina','Estados Unidos','Canadá','México','França','Itália','Espanha','Portugal','Alemanha',
      'Inglaterra','Japão','China','Índia','Rússia','Egito','Austrália','Grécia','Holanda','Suíça','Suécia','Noruega',
      'Chile','Peru','Colômbia','Uruguai','Paraguai','Bolívia','Venezuela','África do Sul','Nigéria','Marrocos',
      'Turquia','Coreia do Sul','Tailândia','Indonésia','Vietnã','Cuba','Jamaica','Irlanda','Escócia','Polônia',
      'Áustria','Bélgica','Dinamarca','Finlândia','Nova Zelândia','Israel'] },
  { id: 'esportes',   emoji: '⚽', name: 'Esportes',    free: true,
    words: ['Futebol','Vôlei','Basquete','Tênis','Natação','Surfe','Boxe','Judô','Karatê','Ciclismo','Corrida',
      'Maratona','Ginástica','Handebol','Rugby','Golfe','Boliche','Hipismo','Esgrima','Escalada','Patinação',
      'Mergulho','Esqui','Snowboard','Ping-Pong','Sinuca','Xadrez','Automobilismo','Motocross','Paraquedismo',
      'Capoeira','Jiu-Jitsu','Muay Thai','Atletismo','Badminton','Triatlo','Beisebol','Futebol Americano','Hóquei',
      'Remo','Damas','Pôquer','Halterofilismo','Arco e Flecha'] },
  { id: 'emocoes',    emoji: '😀', name: 'Emoções',     free: true,
    words: ['Alegria','Tristeza','Raiva','Medo','Nojo','Surpresa','Amor','Ódio','Ciúme','Inveja','Vergonha','Orgulho',
      'Culpa','Ansiedade','Felicidade','Saudade','Esperança','Curiosidade','Tédio','Empolgação','Calma','Nervosismo',
      'Coragem','Timidez','Frustração','Gratidão','Solidão','Paixão','Euforia','Confusão','Alívio','Pânico','Decepção',
      'Compaixão','Admiração','Desânimo','Entusiasmo','Espanto','Melancolia','Susto'] },
  { id: 'instrumentos', emoji: '🎸', name: 'Instrumentos', free: true,
    words: ['Violão','Piano','Sanfona','Tambor','Guitarra','Bateria','Flauta','Violino','Violoncelo','Saxofone',
      'Trompete','Trombone','Clarinete','Gaita','Pandeiro','Cavaquinho','Bandolim','Contrabaixo','Harpa','Órgão',
      'Acordeão','Berimbau','Cuíca','Tamborim','Reco-reco','Agogô','Triângulo','Xilofone','Marimba','Ukulele','Banjo',
      'Teclado','Oboé','Fagote','Tuba','Trompa','Maracas','Djembe','Surdo','Castanhola','Gongo','Chocalho','Zabumba',
      'Viola Caipira'] },
  { id: 'transporte', emoji: '🚗', name: 'Transporte',  free: true,
    words: ['Carro','Ônibus','Avião','Trem','Barco','Navio','Moto','Bicicleta','Caminhão','Helicóptero','Foguete',
      'Submarino','Canoa','Jangada','Balão','Patinete','Skate','Patins','Trator','Ambulância','Táxi','Van',
      'Caminhonete','Lancha','Iate','Jet Ski','Teleférico','Bonde','Charrete','Carroça','Triciclo','Monociclo',
      'Caiaque','Dirigível','Nave Espacial','Carruagem','Vagão','Funicular','Hidroavião','Veleiro','Catamarã',
      'Zeppelin','Segway','Escuna'] },
  { id: 'frutas',     emoji: '🍓', name: 'Frutas',      free: true,
    words: ['Banana','Maçã','Laranja','Uva','Morango','Abacaxi','Melancia','Melão','Manga','Mamão','Goiaba','Pêssego',
      'Ameixa','Cereja','Kiwi','Abacate','Coco','Limão','Tangerina','Caju','Acerola','Maracujá','Jabuticaba','Pitanga',
      'Carambola','Figo','Romã','Framboesa','Amora','Mirtilo','Pera','Nectarina','Lichia','Graviola','Cupuaçu','Pinha',
      'Jaca','Caqui','Tamarindo','Bergamota','Groselha','Cacau','Damasco','Guaraná'] },
  { id: 'roupas',     emoji: '👕', name: 'Roupas',      free: true,
    words: ['Camiseta','Calça','Vestido','Saia','Shorts','Blusa','Casaco','Jaqueta','Moletom','Suéter','Terno',
      'Gravata','Cachecol','Luva','Meia','Sapato','Bota','Sandália','Chinelo','Boné','Chapéu','Óculos','Cinto',
      'Biquíni','Sunga','Maiô','Pijama','Roupão','Avental','Lenço','Touca','Salto Alto','Sapatilha','Colete','Regata',
      'Cueca','Sutiã','Bermuda','Camisa','Poncho','Quimono','Anel','Colar','Pulseira'] },
  { id: 'ferramentas', emoji: '🔧', name: 'Ferramentas', free: true,
    words: ['Martelo','Chave de Fenda','Chave Inglesa','Alicate','Serrote','Furadeira','Parafusadeira','Trena','Nível',
      'Prego','Parafuso','Porca','Lixa','Formão','Enxada','Pá','Picareta','Foice','Machado','Marreta','Espátula',
      'Pincel','Broca','Serra','Esmeril','Torno','Grampeador','Régua','Esquadro','Compasso','Tesoura','Estilete',
      'Chave de Boca','Maçarico','Betoneira','Carrinho de Mão','Serra Elétrica','Morsa','Talhadeira','Ferro de Solda',
      'Cavadeira','Ancinho','Rolo de Pintura','Arruela'] },
  { id: 'natureza',   emoji: '🌿', name: 'Natureza',    free: true,
    words: ['Sol','Estrela','Arco-íris','Relâmpago','Trovão','Tempestade','Neve','Chuva','Nuvem','Vento','Neblina',
      'Furacão','Tornado','Terremoto','Maremoto','Orvalho','Granizo','Aurora Boreal','Eclipse','Meteoro','Cometa',
      'Onda','Maré','Fogo','Cristal','Pôr do Sol','Céu','Galáxia','Buraco Negro','Planeta','Constelação','Nebulosa',
      'Geada','Cratera','Fumaça','Lava','Riacho','Duna','Recife','Penhasco','Vale','Savana','Iceberg','Bruma'] },
  { id: 'superherois', emoji: '🦸', name: 'Super-heróis', free: true,
    words: ['Homem-Aranha','Batman','Superman','Homem de Ferro','Hulk','Mulher-Maravilha','Pantera Negra',
      'Capitão América','Thor','Flash','Aquaman','Lanterna Verde','Ciborgue','Robin','Batgirl','Supergirl','Wolverine',
      'Ciclope','Fênix','Fera','Noturno','Gambit','Vampira','Professor Xavier','Feiticeira Escarlate','Visão',
      'Viúva Negra','Gavião Arqueiro','Doutor Estranho','Capitã Marvel','Homem-Formiga','Vespa','Groot',
      'Rocket Raccoon','Senhor das Estrelas','Demolidor','Justiceiro','Cavaleiro da Lua','Motoqueiro Fantasma',
      'Shazam','Arqueiro Verde','Mercúrio','Duende Verde','Coringa'] },
]

export function buildDeck(packIds) {
  let pool = []
  PACKS.filter(p => packIds.includes(p.id)).forEach(p => { pool = pool.concat(p.words) })
  if (!pool.length) pool = PACKS[0].words.slice()
  pool = [...new Set(pool)] // remove duplicatas entre pacotes (ex.: "Tubarão")
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]]
  }
  return pool
}

// Retorna o tema (pacote) de uma palavra entre os pacotes selecionados.
// Para palavras em mais de um pacote (ex.: "Tubarão"), usa o primeiro na ordem de PACKS.
export function themeForWord(word, packIds) {
  const selected = PACKS.filter(p => packIds.includes(p.id))
  const list = selected.length ? selected : [PACKS[0]]
  const pack = list.find(p => p.words.includes(word))
  return pack ? { name: pack.name, emoji: pack.emoji } : null
}
